### ISSUE TITLE
Running schema.sql errors out with missing UUID extension

### ISSUE THREAD

**Issue by ozgune** [citusdata/citus-example-ad-analytics#3] opened 2017-08-01 15:47 UTC
This question recently came up in our Slack channel; and I'm opening an issue to document it here.

I used the instructions on the Citus website, and started up a cluster using the Docker instructions on our website. When I try to create the schema.sql, I get an error message saying that the UUID extension is missing:

<pre>
postgres=# \i schema.sql
psql:schema.sql:8: ERROR:  function uuid_generate_v4() does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:schema.sql:18: ERROR:  function uuid_generate_v4() does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
psql:schema.sql:20: ERROR:  relation "stores" does not exist
LINE 1: SELECT create_distributed_table('stores', 'store_id');
                                        ^
</pre>

**Comment by ozgune** [comment] 2017-08-01 15:51
To workaround this issue, I ran the following command to create the extension.

<pre>
CREATE EXTENSION "uuid-ossp";
</pre>

However, I needed to run this command on the coordinator and worker nodes, and the instructions on our website don't describe how to connect to worker nodes. Once we have citus-tools.sql installed by default, we can then create this extension by running `citus_run_on_all_workers`.

**Comment by lfittl** [comment] 2017-08-01 19:34
@ozgune Which `schema.sql` are you talking about - are you sure this is the correct repository?

Note that this app is intended to be set up using `rake db:migrate`, which will create the extension on all nodes, see https://github.com/citusdata/citus-example-ad-analytics/blob/master/db/migrate/20160523211642_initial_tables.rb#L3

Closing this issue since I can't reproduce.

**Closed as completed by lfittl** 2017-08-01 19:34 UTC

**Comment by ozgune** [comment] 2017-08-01 20:00
Good point. I read the following Slack thread and incorrectly assumed that the issue was related to creating the UUID extension: https://citus-public.slack.com/archives/C0XRHT1KJ/p1501590116420676
